# Generated by Django 5.2.6 on 2025-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleartime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
