# Generated by Django 5.2.6 on 2025-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleartime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
    ]
